# Transfer Learning MNIST

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


* Train a simple convnet on the MNIST dataset the first 5 digits [0..4].
* Freeze convolutional layers and fine-tune dense layers for the classification of digits [5..9].

### Import MNIST data and create 2 datasets with one dataset having digits from 0 to 4 and other from 5 to 9 

In [0]:
import keras

In [0]:

from keras.backend import backend


#### Import the mnist dataset from keras datasets

In [0]:
from keras.datasets import mnist

In [0]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

Check
**Verify shapes of x_train, y_train, x_test and y_test for both the datasets with the below given shapes **

In [43]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


#### Creating two datasets one with digits below 5 and one with 5 and above

In [0]:
x_train_lt5 = x_train[y_train < 5]
y_train_lt5 = y_train[y_train < 5]
x_test_lt5 = x_test[y_test < 5]
y_test_lt5 = y_test[y_test < 5]

x_train_gt5 = x_train[y_train >= 5]
y_train_gt5 = y_train[y_train >= 5] - 5  # make classes start at 0 for
x_test_gt5 = x_test[y_test >= 5]         # np_utils.to_categorical
y_test_gt5 = y_test[y_test >= 5] - 5

### Check 

Verify shapes of x_train, y_train, x_test and y_test for both the datasets with the below given shapes.

In [45]:
print(x_train_lt5.shape)
print(y_train_lt5.shape)
print(x_test_lt5.shape)
print(y_test_lt5.shape)

(30596, 28, 28)
(30596,)
(5139, 28, 28)
(5139,)


In [46]:
print(x_train_gt5.shape)
print(y_train_gt5.shape)
print(x_test_gt5.shape)
print(y_test_gt5.shape)

(29404, 28, 28)
(29404,)
(4861, 28, 28)
(4861,)


### Let us take only the dataset (x_train, y_train, x_test, y_test) for Integers 0 to 4 in MNIST
### Reshape x_train and x_test to a 4 Dimensional array (channel = 1) to pass it into a Conv2D layer

In [0]:
x_train_lt5=x_train_lt5.reshape(x_train_lt5.shape[0],28,28,1)
x_test_lt5=x_test_lt5.reshape(x_test_lt5.shape[0],28,28,1)

### Change into float32 datatype and Normalize x_train and x_test by dividing it by 255.0

In [0]:
x_train_lt5=x_train_lt5.astype('float32')
x_test_lt5=x_test_lt5.astype('float32')

In [0]:
x_train_lt5 /=255.0
x_test_lt5 /=255.0

### Check

Verify the shapes of the X_train and X_test with the shapes given below.

In [50]:
print('X_train shape:', x_train_lt5.shape)
print('X_test shape:', x_test_lt5.shape)

X_train shape: (30596, 28, 28, 1)
X_test shape: (5139, 28, 28, 1)


### Use One-hot encoding to divide y_train and y_test into required no of output classes

In [0]:
y_train_lt5 = keras.utils.to_categorical(y_train_lt5,num_classes=10)
y_test_lt5 = keras.utils.to_categorical(y_test_lt5,num_classes=10)

### Build a sequential model with 2 Convolutional layers with 32 kernels of size (3,3) followed by a Max pooling layer of size (2,2) followed by a drop out layer to be trained for classification of digits 0-4  

In [0]:
from keras.models import Sequential
from keras.layers import Conv2D,MaxPool2D
from keras.layers import Dense, Flatten, Dropout


In [0]:
model = Sequential()

model.add(Conv2D(filters=32,kernel_size=(3,3),activation='relu',input_shape=(28,28,1)))

model.add(Conv2D(64, (3, 3), activation='relu'))

model.add(MaxPool2D(pool_size= (2,2)))

model.add(Dropout(0.25))





### Post that flatten the data and add 2 Dense layers with 128 neurons and neurons = output classes with activation = 'relu' and 'softmax' respectively. Add dropout layer inbetween if necessary  

In [0]:
#Flatten the layer
model.add(Flatten())

#Add Fully Connected Layer with 128 units and activation function as 'ReLU'
model.add(Dense(128, activation='relu'))

#Apply Dropout with 0.5 probability 
model.add(Dropout(0.5))

#Add Fully Connected Layer with 10 units and activation function as 'softmax'
model.add(Dense(10, activation='softmax'))

### Print the training and test accuracy for 5 epochs

In [56]:
from keras.optimizers import Adam
from keras.losses import categorical_crossentropy

#To use adam optimizer for learning weights with learning rate = 0.001
optimizer = Adam(lr=0.001)
#Set the loss function and optimizer for the model training
model.compile(loss=categorical_crossentropy,
              optimizer=optimizer,
              metrics=['accuracy'])

In [57]:
model.fit(x_train_lt5, y_train_lt5,
          batch_size=128,
          epochs=5,
          verbose=1,
          validation_data=(x_test_lt5, y_test_lt5),
          )

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 30596 samples, validate on 5139 samples
Epoch 1/5





30596/30596 [==============================] - 12s 397us/step - loss: 0.1440 - acc: 0.9550 - val_loss: 0.0167 - val_acc: 0.9938
Epoch 2/5
30596/30596 [==============================] - 5s 147us/step - loss: 0.0380 - acc: 0.9885 - val_loss: 0.0098 - val_acc: 0.9969
Epoch 3/5
30596/30596 [==============================] - 5s 149us/step - loss: 0.0242 - acc: 0.9926 - val_loss: 0.0084 - val_acc: 0.9969
Epoch 4/5
30596/30596 [==============================] - 4s 146us/step - loss: 0.0194 - acc: 0.9942 - val_loss: 0.0084 - val_acc: 0.9961
Epoch 5/5
30596/30596 [==============================] - 5s 148us/step - loss: 0.0154 - acc: 0.9951 - val_loss: 0.0059 - val_acc: 0.9979


### Use the model trained on 0 to 4 digit classification and train it on the dataset which has digits 5 to 9  (Using Transfer learning keeping only the dense layers to be trainable)

### Make only the dense layers to be trainable and convolutional layers to be non-trainable

#### Check model summary to see model layer names

In [58]:
for layers in model.layers:
    print(layers.name)
    if('dense' not in layers.name):
        layers.trainable = False
        print(layers.name + 'is not trainable\n')
    if('dense' in layers.name):
        print(layers.name + ' is trainable\n')

conv2d_7
conv2d_7is not trainable

conv2d_8
conv2d_8is not trainable

max_pooling2d_4
max_pooling2d_4is not trainable

dropout_3
dropout_3is not trainable

flatten_5
flatten_5is not trainable

dense_2
dense_2 is trainable

dropout_4
dropout_4is not trainable

dense_3
dense_3 is trainable



### Do the required preprocessing for `x_train_gt5` also same as `x_train_lt5` and for `y_train_gt5` same as `y_train_lt5`

1. Reshape
2. Change to float32 datatype
3. Normalize (dividing with 255)
4. y_train and y_test Convert into one-hot vectors

In [0]:
x_train_gt5 = x_train_gt5.reshape(x_train_gt5.shape[0],28,28,1)
x_test_gt5 = x_test_gt5.reshape(x_test_gt5.shape[0],28,28,1)

In [0]:
x_train_gt5=x_train_gt5.astype('float32')
x_test_gt5=x_test_gt5.astype('float32')

In [0]:
x_train_gt5 /= 255.0
x_test_gt5 /= 255.0


### Check

Verify the shapes with the given below.

In [0]:
y_train_gt5 = keras.utils.to_categorical(y_train_gt5,num_classes=10)
y_test_gt5 = keras.utils.to_categorical(y_test_gt5,num_classes=10)

In [64]:
print(x_train_gt5.shape)
print(y_train_gt5.shape)
print(x_test_gt5.shape)
print(y_test_gt5.shape)

(29404, 28, 28, 1)
(29404,)
(4861, 28, 28, 1)
(4861,)


## Print the accuracy for classification of digits 5 to 9

In [72]:
model.fit(x_train_gt5,y_train_gt5
          ,batch_size=128
          ,epochs=5
          ,verbose=1
          ,validation_data=(x_test_gt5,y_test_gt5)
          )

Train on 29404 samples, validate on 4861 samples
Epoch 1/5
  768/29404 [..............................] - ETA: 5s - loss: 3.1595 - acc: 0.4466

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py:493: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'


29404/29404 [==============================] - 4s 151us/step - loss: 0.2446 - acc: 0.9364 - val_loss: 0.0379 - val_acc: 0.9881
Epoch 2/5
29404/29404 [==============================] - 4s 148us/step - loss: 0.0608 - acc: 0.9814 - val_loss: 0.0278 - val_acc: 0.9895
Epoch 3/5
29404/29404 [==============================] - 4s 144us/step - loss: 0.0435 - acc: 0.9864 - val_loss: 0.0245 - val_acc: 0.9914
Epoch 4/5
29404/29404 [==============================] - 4s 148us/step - loss: 0.0344 - acc: 0.9890 - val_loss: 0.0220 - val_acc: 0.9938
Epoch 5/5
29404/29404 [==============================] - 4s 147us/step - loss: 0.0307 - acc: 0.9903 - val_loss: 0.0248 - val_acc: 0.9940


In [112]:
model.evaluate(x_test_gt5,y_test_gt5)

4861/4861 [==============================] - 1s 129us/step


[0.024754007477785715, 0.9940341493519852]

# Text classification using TF-IDF

###  Load the dataset from sklearn.datasets

In [0]:
from sklearn.datasets import fetch_20newsgroups

In [0]:
categories = ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']

### Training data

In [75]:
twenty_train = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)

### Test data

In [0]:
twenty_test = fetch_20newsgroups(subset='test', categories=categories, shuffle=True, random_state=42)

###  a.  You can access the values for the target variable using .target attribute 
###  b. You can access the name of the class in the target variable with .target_names


In [77]:
twenty_train.target

array([1, 1, 3, ..., 2, 2, 2])

In [78]:
twenty_train.target_names

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [88]:
twenty_train.data[:4]

['From: sd345@city.ac.uk (Michael Collier)\nSubject: Converting images to HP LaserJet III?\nNntp-Posting-Host: hampton\nOrganization: The City University\nLines: 14\n\nDoes anyone know of a good way (standard PC application/PD utility) to\nconvert tif/img/tga files into LaserJet III format.  We would also like to\ndo the same, converting to HPGL (HP plotter) files.\n\nPlease email any response.\n\nIs this the correct group?\n\nThanks in advance.  Michael.\n-- \nMichael Collier (Programmer)                 The Computer Unit,\nEmail: M.P.Collier@uk.ac.city                The City University,\nTel: 071 477-8000 x3769                      London,\nFax: 071 477-8565                            EC1V 0HB.\n',
 "From: ani@ms.uky.edu (Aniruddha B. Deglurkar)\nSubject: help: Splitting a trimming region along a mesh \nOrganization: University Of Kentucky, Dept. of Math Sciences\nLines: 28\n\n\n\n\tHi,\n\n\tI have a problem, I hope some of the 'gurus' can help me solve.\n\n\tBackground of the probl

### Now with dependent and independent data available for both train and test datasets, using TfidfVectorizer fit and transform the training data and test data and get the tfidf features for both

In [81]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()
import pandas as pd
pd.DataFrame(vect.fit_transform(twenty_train).toarray(), columns=vect.get_feature_names())

data  descr  filenames  target  target_names
0   1.0    0.0        0.0     0.0           0.0
1   0.0    0.0        1.0     0.0           0.0
2   0.0    0.0        0.0     0.0           1.0
3   0.0    0.0        0.0     1.0           0.0
4   0.0    1.0        0.0     0.0           0.0

In [97]:
twenty_train.target

array([1, 1, 3, ..., 2, 2, 2])

In [0]:
import numpy as np
x_train_tfif=np.array(vect.fit_transform(twenty_train.data).toarray())
y_train_tfif=twenty_train.target

In [0]:
x_test_tfif=np.array(vect.transform(twenty_test.data).toarray())
y_test_tfif=twenty_test.target

### Use logisticRegression with tfidf features as input and targets as output and train the model and report the train and test accuracy score

In [101]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression(C=1e9)
lr.fit(x_train_tfif,y_train_tfif)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1000000000.0, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [103]:
from sklearn import metrics

metrics.accuracy_score(y_test_tfif, lr.predict(x_test_tfif))

0.9260985352862849

In [104]:
metrics.confusion_matrix(y_test_tfif, lr.predict(x_test_tfif))

array([[271,   6,   8,  34],
       [  3, 377,   5,   4],
       [  6,  25, 361,   4],
       [  6,   8,   2, 382]])

In [110]:
metrics.recall_score(y_test_tfif, lr.predict(x_test_tfif),average='weighted')

0.9260985352862849